In [1]:
using Oscar

 -----    -----    -----      -      -----   
|     |  |     |  |     |    | |    |     |  
|     |  |        |         |   |   |     |  
|     |   -----   |        |     |  |-----   
|     |        |  |        |-----|  |   |    
|     |  |     |  |     |  |     |  |    |   
 -----    -----    -----   -     -  -     -  

...combining (and extending) ANTIC, GAP, Polymake and Singular
Version 0.10.1 ... 
 ... which comes with absolutely no warranty whatsoever
Type: '?Oscar' for more information
(c) 2019-2022 by The Oscar Development Team


In [4]:
F = PolyhedralFan([-2 1; 0 1; 2 1],IncidenceMatrix([[1,2],[2,3]]))

A polyhedral fan in ambient dimension 2

In [6]:
F.pm_fan.PURE

true

In [8]:
F.pm_fan.FULL_DIM

true

In [9]:
cones(F,1)

3-element SubObjectIterator{Cone{fmpq}}:
 A polyhedral cone in ambient dimension 2
 A polyhedral cone in ambient dimension 2
 A polyhedral cone in ambient dimension 2

In [10]:
maxCones = maximal_cones(F)

2-element SubObjectIterator{Cone{fmpq}}:
 A polyhedral cone in ambient dimension 2
 A polyhedral cone in ambient dimension 2

In [11]:
pmFan = F.pm_fan

type: PolyhedralFan<Rational>

COMBINATORIAL_DIM
	1

FACET_NORMALS
	1 2
	-1 0
	-1 2

FAN_AMBIENT_DIM
	2

FAN_DIM
	2

FULL_DIM
	true

HASSE_DIAGRAM
	type: Lattice<BasicDecoration, Nonsequential> as PolyhedralFan<Rational>::HASSE_DIAGRAM

INPUT_CONES
	{0 1}
	{1 2}

INPUT_RAYS
	-2 1
	0 1
	2 1

LINEALITY_DIM
	0

LINEALITY_SPACE
	

LINEAR_SPAN_NORMALS
	

MAXIMAL_CONES
	{0 1}
	{1 2}

MAXIMAL_CONES_COMBINATORIAL_DIMS
	1 1

MAXIMAL_CONES_FACETS
	1 1 0
	0 -1 1

MAXIMAL_CONES_INCIDENCES
	<{0}
	{1}
	>
	<{1}
	{2}
	>

MAXIMAL_CONES_LINEAR_SPAN_NORMALS
	{}
	{}

N_FACET_NORMALS
	3

N_MAXIMAL_CONES
	2

PURE
	true

RAYS
	-1 1/2
	0 1
	1 1/2

In [12]:
HD = pmFan.HASSE_DIAGRAM

type: Lattice<BasicDecoration, Nonsequential> as PolyhedralFan<Rational>::HASSE_DIAGRAM

ADJACENCY
	{}
	{0}
	{0}
	{1}
	{1 2}
	{2}
	{3 4 5}

BOTTOM_NODE
	6

DECORATION
	({-1} 3)
	({0 1} 2)
	({1 2} 2)
	({0} 1)
	({1} 1)
	({2} 1)
	({} 0)

INVERSE_RANK_MAP
	{(0 {6}) (1 {3 4 5}) (2 {1 2}) (3 {0})}

TOP_NODE
	0

In [13]:
pmFan.COMPLETE

false

In [14]:
pmFan

type: PolyhedralFan<Rational>

COMBINATORIAL_DIM
	1

COMPLETE
	false

DUAL_GRAPH
	type: Graph<Undirected>

FACET_NORMALS
	1 2
	-1 0
	-1 2

FAN_AMBIENT_DIM
	2

FAN_DIM
	2

FULL_DIM
	true

HASSE_DIAGRAM
	type: Lattice<BasicDecoration, Nonsequential> as PolyhedralFan<Rational>::HASSE_DIAGRAM

INPUT_CONES
	{0 1}
	{1 2}

INPUT_RAYS
	-2 1
	0 1
	2 1

INTERSECTION_COMPLEX
	type: SimplicialComplex

LINEALITY_DIM
	0

LINEALITY_SPACE
	

LINEAR_SPAN_NORMALS
	

MAXIMAL_CONES
	{0 1}
	{1 2}

MAXIMAL_CONES_COMBINATORIAL_DIMS
	1 1

MAXIMAL_CONES_FACETS
	1 1 0
	0 -1 1

MAXIMAL_CONES_INCIDENCES
	<{0}
	{1}
	>
	<{1}
	{2}
	>

MAXIMAL_CONES_LINEAR_SPAN_NORMALS
	{}
	{}

N_FACET_NORMALS
	3

N_MAXIMAL_CONES
	2

PURE
	true

RAYS
	-1 1/2
	0 1
	1 1/2

SIMPLICIAL
	true

In [15]:
adj = HD.ADJACENCY

pm::graph::Graph<pm::graph::Directed>
{}
{0}
{0}
{1}
{1 2}
{2}
{3 4 5}


In [16]:
HD.DECORATION

PropertyValue wrapping pm::graph::NodeMap<pm::graph::Directed, polymake::graph::lattice::BasicDecoration>
({-1} 3)
({0 1} 2)
({1 2} 2)
({0} 1)
({1} 1)
({2} 1)
({} 0)


In [18]:
Polymake.graph.nodes_of_rank(HD, 1)

PropertyValue wrapping std::__cxx11::list<long, std::allocator<long> >
{3 4 5}

In [19]:
maxCones

2-element SubObjectIterator{Cone{fmpq}}:
 A polyhedral cone in ambient dimension 2
 A polyhedral cone in ambient dimension 2

In [21]:
c1 = maxCones[1]
c2 = maxCones[2]

A polyhedral cone in ambient dimension 2

In [44]:
i = intersect(c1, c2)

A polyhedral cone in ambient dimension 2

In [24]:
dim(i) == dim(c1)-1

true

In [25]:
i

A polyhedral cone in ambient dimension 2

In [45]:
pdi = polarize(i)

A polyhedral cone in ambient dimension 2

In [27]:
i

A polyhedral cone in ambient dimension 2

In [28]:
rays(i)

1-element SubObjectIterator{RayVector{fmpq}}:
 [0, 1]

In [29]:
polarize(i)

LoadError: initial check failed: 
invalid input: zero vector is not a valid entry for INPUT_RAYS at /home/lars/.julia/artifacts/e8b92adf0c63efefd4d6e7f697525c23844133fa/share/polymake/apps/polytope/rules/initial.rules line 63.
	Polymake::polytope::Cone::__prod__aab475(Polymake::polytope::Cone__Rational=ARRAY(0x1b6d6b28)) called at /home/lars/.julia/artifacts/e8b92adf0c63efefd4d6e7f697525c23844133fa/share/polymake/perllib/Polymake/Core/Rule.pm line 852
	eval {...} called at /home/lars/.julia/artifacts/e8b92adf0c63efefd4d6e7f697525c23844133fa/share/polymake/perllib/Polymake/Core/Rule.pm line 844
	Polymake::Core::Rule::execute_me called at /home/lars/.julia/artifacts/e8b92adf0c63efefd4d6e7f697525c23844133fa/share/polymake/perllib/Polymake/Core/Rule.pm line 837
	Polymake::Core::Rule::execute(Polymake::Core::Rule=ARRAY(0x15f939f0), Polymake::polytope::Cone__Rational=ARRAY(0x1b6d6b28), 1) called at /home/lars/.julia/artifacts/e8b92adf0c63efefd4d6e7f697525c23844133fa/share/polymake/perllib/Polymake/Core/Scheduler.pm line 225
	Polymake::Core::Scheduler::RuleDeputy::execute(Polymake::Core::Scheduler::RuleDeputy=ARRAY(0x1b81af08), Polymake::polytope::Cone__Rational=ARRAY(0x1b6d6b28), 1) called at /home/lars/.julia/artifacts/e8b92adf0c63efefd4d6e7f697525c23844133fa/share/polymake/perllib/Polymake/Core/Scheduler.pm line 593
	Polymake::Core::Scheduler::TentativeRuleChain::execute(Polymake::Core::Scheduler::TentativeRuleChain=ARRAY(0x1a8275e0), Polymake::polytope::Cone__Rational=ARRAY(0x1b6d6b28)) called at /home/lars/.julia/artifacts/e8b92adf0c63efefd4d6e7f697525c23844133fa/share/polymake/perllib/Polymake/Core/Scheduler.pm line 1536
	Polymake::Core::Scheduler::InitRuleChain::resolve(Polymake::Core::Scheduler::InitRuleChain=ARRAY(0x1a90c2c8)) called at /home/lars/.julia/artifacts/e8b92adf0c63efefd4d6e7f697525c23844133fa/share/polymake/perllib/Polymake/Core/Scheduler.pm line 1638
	Polymake::Core::Scheduler::resolve_initial_request(Polymake::polytope::Cone__Rational=ARRAY(0x1b6d6b28), ARRAY(0x19f21448)) called at /home/lars/.julia/artifacts/e8b92adf0c63efefd4d6e7f697525c23844133fa/share/polymake/perllib/Polymake/Core/BigObject.pm line 278
	Polymake::Core::InitTransaction::commit(Polymake::Core::RuleTransaction=ARRAY(0x1840fa58), Polymake::polytope::Cone__Rational=ARRAY(0x1b6d6b28)) called at /home/lars/.julia/artifacts/e8b92adf0c63efefd4d6e7f697525c23844133fa/share/polymake/perllib/Polymake/Core/BigObject.pm line 1391
	Polymake::Core::BigObject::commit(Polymake::polytope::Cone__Rational=ARRAY(0x1b6d6b28)) called at /home/lars/.julia/artifacts/e8b92adf0c63efefd4d6e7f697525c23844133fa/share/polymake/perllib/Polymake/Core/CPlusPlus.pm line 992
	eval {...} called at /home/lars/.julia/artifacts/e8b92adf0c63efefd4d6e7f697525c23844133fa/share/polymake/perllib/Polymake/Core/CPlusPlus.pm line 992
	Polymake::Core::CPlusPlus::perApplication::__ANON__ called at /home/lars/.julia/artifacts/e8b92adf0c63efefd4d6e7f697525c23844133fa/share/polymake/perllib/Polymake/Overload.pm line 789
	Polymake::polytope::polarize(Polymake::polytope::Cone__Rational=ARRAY(0x182157d0), HASH(0x1bc22be8)) called at -e line 0
	eval {...} called at -e line 0



In [30]:
Polymake.polytope.polarize(i.pm_cone)

LoadError: initial check failed: 
invalid input: zero vector is not a valid entry for INPUT_RAYS at /home/lars/.julia/artifacts/e8b92adf0c63efefd4d6e7f697525c23844133fa/share/polymake/apps/polytope/rules/initial.rules line 63.
	Polymake::polytope::Cone::__prod__aab475(Polymake::polytope::Cone__Rational=ARRAY(0x1b6d6c00)) called at /home/lars/.julia/artifacts/e8b92adf0c63efefd4d6e7f697525c23844133fa/share/polymake/perllib/Polymake/Core/Rule.pm line 852
	eval {...} called at /home/lars/.julia/artifacts/e8b92adf0c63efefd4d6e7f697525c23844133fa/share/polymake/perllib/Polymake/Core/Rule.pm line 844
	Polymake::Core::Rule::execute_me called at /home/lars/.julia/artifacts/e8b92adf0c63efefd4d6e7f697525c23844133fa/share/polymake/perllib/Polymake/Core/Rule.pm line 837
	Polymake::Core::Rule::execute(Polymake::Core::Rule=ARRAY(0x15f939f0), Polymake::polytope::Cone__Rational=ARRAY(0x1b6d6c00), 1) called at /home/lars/.julia/artifacts/e8b92adf0c63efefd4d6e7f697525c23844133fa/share/polymake/perllib/Polymake/Core/Scheduler.pm line 225
	Polymake::Core::Scheduler::RuleDeputy::execute(Polymake::Core::Scheduler::RuleDeputy=ARRAY(0x18266bd8), Polymake::polytope::Cone__Rational=ARRAY(0x1b6d6c00), 1) called at /home/lars/.julia/artifacts/e8b92adf0c63efefd4d6e7f697525c23844133fa/share/polymake/perllib/Polymake/Core/Scheduler.pm line 593
	Polymake::Core::Scheduler::TentativeRuleChain::execute(Polymake::Core::Scheduler::TentativeRuleChain=ARRAY(0x1ab7ec40), Polymake::polytope::Cone__Rational=ARRAY(0x1b6d6c00)) called at /home/lars/.julia/artifacts/e8b92adf0c63efefd4d6e7f697525c23844133fa/share/polymake/perllib/Polymake/Core/Scheduler.pm line 1536
	Polymake::Core::Scheduler::InitRuleChain::resolve(Polymake::Core::Scheduler::InitRuleChain=ARRAY(0x182b0d30)) called at /home/lars/.julia/artifacts/e8b92adf0c63efefd4d6e7f697525c23844133fa/share/polymake/perllib/Polymake/Core/Scheduler.pm line 1638
	Polymake::Core::Scheduler::resolve_initial_request(Polymake::polytope::Cone__Rational=ARRAY(0x1b6d6c00), ARRAY(0x17e7f440)) called at /home/lars/.julia/artifacts/e8b92adf0c63efefd4d6e7f697525c23844133fa/share/polymake/perllib/Polymake/Core/BigObject.pm line 278
	Polymake::Core::InitTransaction::commit(Polymake::Core::RuleTransaction=ARRAY(0x1b81b550), Polymake::polytope::Cone__Rational=ARRAY(0x1b6d6c00)) called at /home/lars/.julia/artifacts/e8b92adf0c63efefd4d6e7f697525c23844133fa/share/polymake/perllib/Polymake/Core/BigObject.pm line 1391
	Polymake::Core::BigObject::commit(Polymake::polytope::Cone__Rational=ARRAY(0x1b6d6c00)) called at /home/lars/.julia/artifacts/e8b92adf0c63efefd4d6e7f697525c23844133fa/share/polymake/perllib/Polymake/Core/CPlusPlus.pm line 992
	eval {...} called at /home/lars/.julia/artifacts/e8b92adf0c63efefd4d6e7f697525c23844133fa/share/polymake/perllib/Polymake/Core/CPlusPlus.pm line 992
	Polymake::Core::CPlusPlus::perApplication::__ANON__ called at /home/lars/.julia/artifacts/e8b92adf0c63efefd4d6e7f697525c23844133fa/share/polymake/perllib/Polymake/Overload.pm line 789
	Polymake::polytope::polarize(Polymake::polytope::Cone__Rational=ARRAY(0x182157d0), HASH(0x1a90c568)) called at -e line 0
	eval {...} called at -e line 0



In [31]:
i.pm_cone

type: Cone<Rational>
description: Intersection of cones

COMBINATORIAL_DIM
	0

CONE_AMBIENT_DIM
	2

CONE_DIM
	1

EQUATIONS
	

FULL_DIM
	false

INEQUALITIES
   1  2
  -1  0
   1  0
  -1  2

LINEALITY_DIM
	0

LINEALITY_SPACE
	

LINEAR_SPAN
	-1 0

POINTED
	true

RAYS
	0 1

In [32]:
contains(i, [0,0])

true

In [38]:
M = i.pm_cone.HILBERT_BASIS_GENERATORS[1]

pm::Matrix<pm::Integer>
0 1


In [39]:
M[1,:]

pm::Vector<pm::Integer>
0 1

In [40]:
contains(i, M[1,:])

true

In [41]:
?solve_mixed

search: solve_mixed



```
solve_mixed(A::fmpz_mat, b::fmpz_mat, C::fmpz_mat, d::fmpz_mat)
```

Solve $Ax = b$ under $Cx >= d$, assumes a finite solution set.

# Examples

Find all $(x_1, x_2)\in\mathbb{Z}^2$ such that $x_1+x_2=7$, $x_1\ge 2$, and $x_2\ge 3$. The solutions are the rows of the output. Note that the output can be permuted, hence we sort it.

```jldoctest
julia> A = fmpz_mat([1 1]);

julia> b = zero_matrix(FlintZZ, 1,1); b[1,1]=7;

julia> C = fmpz_mat([1 0; 0 1]);

julia> d = zero_matrix(FlintZZ,2,1); d[1,1]=2; d[2,1]=3;

julia> sortslices(Matrix{BigInt}(solve_mixed(A, b, C, d)), dims=1)
3×2 Matrix{BigInt}:
 2  5
 3  4
 4  3
```

---

```
solve_mixed(A::fmpz_mat, b::fmpz_mat, C::fmpz_mat)
```

Solve $Ax = b$ under $Cx >= 0$, assumes a finite solution set.

# Examples

Find all $(x_1, x_2)\in\mathbb{Z}^2_{\ge 0}$ such that $x_1+x_2=3$. The solutions are the rows of the output. Note that the output can be permuted, hence we sort it.

```jldoctest
julia> A = fmpz_mat([1 1]);

julia> b = zero_matrix(FlintZZ, 1,1); b[1,1]=3;

julia> C = fmpz_mat([1 0; 0 1]);

julia> sortslices(Matrix{BigInt}(solve_mixed(A, b, C)), dims=1)
4×2 Matrix{BigInt}:
 0  3
 1  2
 2  1
 3  0
```


In [42]:
M

pm::Matrix<pm::Integer>
0 1


In [43]:
nrows(M)

1

In [46]:
c1

A polyhedral cone in ambient dimension 2

In [47]:
pdc1 = polarize(c1)

A polyhedral cone in ambient dimension 2

In [50]:
hbpdc1 = matrix(ZZ,hilbert_basis(pdc1))

[ 1   2]
[ 0   1]
[-1   0]

In [51]:
hbpdc1 isa fmpz_mat

true

In [52]:
pdi

A polyhedral cone in ambient dimension 2

In [53]:
hbi = pdi.pm_cone.HILBERT_BASIS_GENERATORS

pm::Array<pm::Matrix<pm::Integer>>
<0 1
>
<1 0
>


In [56]:
b = matrix(ZZ, [[-1;0]])

[-1   0]

In [57]:
identity_matrix(ZZ,3)

[1   0   0]
[0   1   0]
[0   0   1]

In [58]:
A = transpose(hbpdc1)

[1   0   -1]
[2   1    0]

In [60]:
C = identity_matrix(ZZ, ncols(A))

[1   0   0]
[0   1   0]
[0   0   1]

In [63]:
b = transpose(b)

[-1]
[ 0]

In [64]:
d = zero_matrix(ZZ, ncols(A), 1)

[0]
[0]
[0]

In [65]:
solve_mixed(A,b,C,d)

[0   0   1]

In [84]:
C[3,3]=0
C

[1   0   0]
[0   1   0]
[0   0   0]

In [85]:
solve_mixed(A,b,C,d)

[0   0   1]

In [66]:
M

pm::Matrix<pm::Integer>
0 1


In [72]:
transpose(matrix(ZZ, [Vector{Int}(M[1,:])]))

[0]
[1]

In [73]:
?toric_ideal

search: toric_ideal



```
toric_ideal(pts::fmpz_mat)
```

Return the toric ideal generated from the linear relations between the points `pts`. This is the ideal generated by the set of binomials $\{x^u-x^v\ |\ u,v\in\mathbb{Z}^n_{\ge 0}\ (pts)^T\cdot(u-v)=0\}$

# Examples

```jldoctest
julia> C = positive_hull([-2 5; 1 0]);

julia> H = hilbert_basis(C);

julia> toric_ideal(H)
ideal(x2*x3 - x4^2, -x1*x3 + x2^2*x4, -x1*x4 + x2^3, -x1*x3^2 + x2*x4^3, -x1*x3^3 + x4^5)
```

---

```
toric_ideal(R::MPolyRing, pts::fmpz_mat)
```

Return the toric ideal generated from the linear relations between the points `pts`. This is the ideal generated by the set of binomials $\{x^u-x^v\ |\ u,v\in\mathbb{Z}^n_{\ge 0}\ (pts)^T\cdot(u-v)=0\}$

# Examples

```jldoctest
julia> C = positive_hull([-2 5; 1 0]);

julia> H = hilbert_basis(C);

julia> R,_ = PolynomialRing(QQ, length(H));

julia> toric_ideal(R, H)
ideal(x2*x3 - x4^2, -x1*x3 + x2^2*x4, -x1*x4 + x2^3, -x1*x3^2 + x2*x4^3, -x1*x3^3 + x4^5)
```

---

```
toric_ideal(R::MPolyRing, antv::AffineNormalToricVariety)
```

Return the toric ideal defining the affine normal toric variety as an ideal in `R`.

# Examples

Take the cone over the square at height one. The resulting toric variety has one defining equation. In projective space this corresponds to $\mathbb{P}^1\times\mathbb{P}^1$. Note that this cone is self-dual, the toric ideal comes from the dual cone.

```jldoctest
julia> C = positive_hull([1 0 0; 1 1 0; 1 0 1; 1 1 1])
A polyhedral cone in ambient dimension 3

julia> antv = AffineNormalToricVariety(C)
A normal, affine toric variety

julia> R,_ = PolynomialRing(QQ, 4);

julia> toric_ideal(R, antv)
ideal(-x1*x2 + x3*x4)
```

---

```
toric_ideal(antv::AffineNormalToricVariety)
```

Return the toric ideal defining the affine normal toric variety.

# Examples

Take the cone over the square at height one. The resulting toric variety has one defining equation. In projective space this corresponds to $\mathbb{P}^1\times\mathbb{P}^1$. Note that this cone is self-dual, the toric ideal comes from the dual cone.

```jldoctest
julia> C = positive_hull([1 0 0; 1 1 0; 1 0 1; 1 1 1])
A polyhedral cone in ambient dimension 3

julia> antv = AffineNormalToricVariety(C)
A normal, affine toric variety

julia> toric_ideal(antv)
ideal(-x1*x2 + x3*x4)
```


In [74]:
HH = matrix(ZZ, [0 1; 1 1; 2 1])

[0   1]
[1   1]
[2   1]

In [75]:
toric_ideal(HH)

ideal(x1*x3 - x2^2)

In [76]:
R = PolynomialRing(QQ, 3)

(Multivariate Polynomial Ring in x1, x2, x3 over Rational Field, fmpq_mpoly[x1, x2, x3])

In [78]:
toric_ideal(R[1], HH)

ideal(x1*x3 - x2^2)

In [79]:
pdi

A polyhedral cone in ambient dimension 2

In [80]:
pdi isa Cone

true

In [81]:
HH

[0   1]
[1   1]
[2   1]

In [86]:
M

pm::Matrix<pm::Integer>
0 1


In [87]:
HH

[0   1]
[1   1]
[2   1]

In [88]:
HH = transpose(HH)

[0   1   2]
[1   1   1]

In [89]:
vmat = HH[:,1]

[0]
[1]

In [90]:
vmat == HH[:,1]

true

In [92]:
gpi= Polymake.ideal.pluecker_ideal(3,5)

type: Ideal

GENERATORS
	x_0*x_5 - x_1*x_4 + x_2*x_3 x_0*x_8 - x_1*x_7 + x_2*x_6 x_0*x_9 - x_3*x_7 + x_4*x_6 x_1*x_9 - x_3*x_8 + x_5*x_6 x_2*x_9 - x_4*x_8 + x_5*x_7

GROEBNER
	type: Groebner as Ideal::GROEBNER

In [93]:
gpi.GENERATORS

pm::Array<pm::Polynomial<pm::Rational, long>>
x_0*x_5 - x_1*x_4 + x_2*x_3 x_0*x_8 - x_1*x_7 + x_2*x_6 x_0*x_9 - x_3*x_7 + x_4*x_6 x_1*x_9 - x_3*x_8 + x_5*x_6 x_2*x_9 - x_4*x_8 + x_5*x_7

In [94]:
gram = QQ[-2 1; 1 -2]

[-2    1]
[ 1   -2]

In [95]:
L = Zlattice(gram=gram)

Quadratic lattice of rank 2 and degree 2 over the rationals

In [96]:
orthogonal_group(L)

Matrix group of degree 2 over Rational Field

In [97]:
genus(L)

ZGenus
Signature: (0, 2)
Genus symbol at 2:   1^-2
Genus symbol at 3:   1^1 3^1